[package]
name = "xtask"
version = "0.1.0"
edition =  "2021"

[dependencies]
anyhow = "1.0.86"
aya-tool = { git = "https://github.com/aya-rs/aya", version = "0.1.0" }
clap = { version = "4.5.4", features = ["derive"] }
